//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glove.IOT.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DeviceParameterInfo
    {
        public DeviceParameterInfo()
        {
            this.SingleProgress = 0;
            this.StatusFlag = 0;
        }
    
        public int Id { get; set; }
        public int DeviceInfoId { get; set; }
        public Nullable<int> NowOutput { get; set; }
        public Nullable<int> TargetOutput { get; set; }
        public Nullable<short> SingleProgress { get; set; }
        public short StatusFlag { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
        public System.DateTime SubTime { get; set; }
    
        public virtual DeviceInfo DeviceInfo { get; set; }
    }
}
