//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glove.IOT.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DeviceHistoryData
    {
        public string Id { get; set; }
        public int DeviceName { get; set; }
        public int NowOutput { get; set; }
        public string StatusFlag { get; set; }
        public int SingleProgress { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
