//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glove.IOT.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DeviceCmd
    {
        public string Id { get; set; }
        public int DeviceName { get; set; }
        public string CmdCode { get; set; }
        public string CmdData { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CmdState { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
    }
}
