//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glove.IOT.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DeviceInfo
    {
        public DeviceInfo()
        {
            this.R_DeviceInfo_DeviceGroupInfo = new HashSet<R_DeviceInfo_DeviceGroupInfo>();
        }
    
        public string Id { get; set; }
        public int DeviceName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public virtual ICollection<R_DeviceInfo_DeviceGroupInfo> R_DeviceInfo_DeviceGroupInfo { get; set; }
    }
}
