//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glove.IOT.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DeviceGroupInfo
    {
        public DeviceGroupInfo()
        {
            this.R_DeviceInfo_DeviceGroupInfo = new HashSet<R_DeviceInfo_DeviceGroupInfo>();
            this.UserInfo = new HashSet<UserInfo>();
        }
    
        public string Id { get; set; }
        public string DeviceGroupName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<R_DeviceInfo_DeviceGroupInfo> R_DeviceInfo_DeviceGroupInfo { get; set; }
        public virtual ICollection<UserInfo> UserInfo { get; set; }
    }
}
