//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glove.IOT.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class OperationLog
    {
        public int Id { get; set; }
        public string UName { get; set; }
        public string ActionType { get; set; }
        public string ActionName { get; set; }
        public string OperationObj { get; set; }
        public string Ip { get; set; }
        public string Mac { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime SubTime { get; set; }
    }
}
