//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glove.IOT.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class R_GroupInfo_DeviceInfo
    {
        public int Id { get; set; }
        public int GroupInfoId { get; set; }
        public int DeviceInfoId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual GroupInfo GroupInfo { get; set; }
        public virtual DeviceInfo DeviceInfo { get; set; }
    }
}
